version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mobile-rent-db
      MYSQL_USER: password
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mobile-rent-mysql-data:/var/lib/mysql  # Persistent data storage
    networks:
      - mobile-rent-network
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - mobile-rent-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - mobile-rent-network
networks:
  mobile-rent-network:
    driver: bridge
volumes:
  mobile-rent-mysql-data:
  mobile-rent-rabbitmq-data: